export const mockProducts = [
  {
    "id": "4f325537-dba0-46e0-8b70-299e30272e76",
    "category": "Painting & Vinyl Wall Covering",
    "colors": "Mauv",
    "photo": "http://dummyimage.com/215x100.png/ff4444/ffffff",
    "name": "Alize Red Passion",
    "price": 86,
    "description": "neque sapien placerat ante nulla justo aliquam quis turpis eget",
    "weight": 53.57,
    "specs": "vivamus in felis eu sapien",
    "branch": "Buzzdog",
    "origin": "fusce consequat nulla nisl nunc nisl duis bibendum felis sed",
    "discount": 3.52,
    "shop": "Zooveo",
    "user": "omerrydew0",
    "createAt": "6/16/2022",
    "slug": "Reverse-engineered",
    "averageRating": 2.17
  },
  {
    "id": "ee74bf13-cda0-4222-a926-d6f250bedecd",
    "category": "Drywall & Acoustical (MOB)",
    "colors": "Pink",
    "photo": "http://dummyimage.com/128x100.png/cc0000/ffffff",
    "name": "Chicken - Soup Base",
    "price": 50,
    "description": "volutpat convallis morbi odio odio elementum eu interdum eu tincidunt",
    "weight": 36.56,
    "specs": "convallis tortor risus dapibus augue vel accumsan tellus",
    "branch": "Fivechat",
    "origin": "amet lobortis sapien sapien non mi integer ac neque",
    "discount": 3.76,
    "shop": "Mydeo",
    "user": "mcattermull1",
    "createAt": "7/19/2022",
    "slug": "bottom-line",
    "averageRating": 4.33
  },
  {
    "id": "f1a0bd8f-3dcd-4afe-8f38-6aa047eb5ceb",
    "category": "Hard Tile & Stone",
    "colors": "Teal",
    "photo": "http://dummyimage.com/137x100.png/dddddd/000000",
    "name": "Carbonated Water - Peach",
    "price": 37,
    "description": "et ultrices posuere cubilia curae",
    "weight": 11.38,
    "specs": "augue vestibulum rutrum rutrum neque",
    "branch": "Jazzy",
    "origin": "nec nisi volutpat eleifend donec ut",
    "discount": 6.36,
    "shop": "Oloo",
    "user": "gcossans2",
    "createAt": "5/27/2022",
    "slug": "Integrated",
    "averageRating": 4.6
  },
  {
    "id": "ff707897-f680-4ecc-bf96-449790ff5d16",
    "category": "RF Shielding",
    "colors": "Crimson",
    "photo": "http://dummyimage.com/232x100.png/ff4444/ffffff",
    "name": "Soup - Boston Clam Chowder",
    "price": 79,
    "description": "ut nunc vestibulum ante ipsum",
    "weight": 32.63,
    "specs": "ipsum aliquam non mauris morbi non",
    "branch": "Devpoint",
    "origin": "varius nulla facilisi cras non",
    "discount": 3.62,
    "shop": "LiveZ",
    "user": "osage3",
    "createAt": "7/21/2022",
    "slug": "Front-line",
    "averageRating": 2.52
  },
  {
    "id": "e854430d-3b39-42b3-8db7-3914396a7e77",
    "category": "RF Shielding",
    "colors": "Violet",
    "photo": "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
    "name": "Wine - Two Oceans Sauvignon",
    "price": 16,
    "description": "duis bibendum morbi non quam nec",
    "weight": 57.46,
    "specs": "dui luctus rutrum nulla tellus in",
    "branch": "Vimbo",
    "origin": "dictumst etiam faucibus cursus urna ut",
    "discount": 5.1,
    "shop": "Skyba",
    "user": "jnutkins4",
    "createAt": "12/2/2021",
    "slug": "homogeneous",
    "averageRating": 3.48
  },
  {
    "id": "f6ae43d1-0a27-44e1-bd8e-b33c7fdaae9b",
    "category": "Roofing (Asphalt)",
    "colors": "Crimson",
    "photo": "http://dummyimage.com/184x100.png/cc0000/ffffff",
    "name": "Wakami Seaweed",
    "price": 10,
    "description": "pulvinar lobortis est phasellus sit amet erat",
    "weight": 31.92,
    "specs": "dui nec nisi volutpat eleifend donec ut",
    "branch": "Viva",
    "origin": "non mattis pulvinar nulla pede ullamcorper augue a suscipit",
    "discount": 4.3,
    "shop": "Twitterlist",
    "user": "ageorgiades5",
    "createAt": "4/7/2022",
    "slug": "Switchable",
    "averageRating": 4.57
  },
  {
    "id": "2338b0b4-99c2-4637-ba59-f878c364269e",
    "category": "Fire Protection",
    "colors": "Violet",
    "photo": "http://dummyimage.com/216x100.png/cc0000/ffffff",
    "name": "Beef - Ox Tongue",
    "price": 53,
    "description": "ante nulla justo aliquam quis turpis eget elit sodales",
    "weight": 66.25,
    "specs": "dui proin leo odio porttitor id consequat in consequat",
    "branch": "Voonyx",
    "origin": "sagittis nam congue risus semper porta volutpat quam pede",
    "discount": 3.64,
    "shop": "Tagopia",
    "user": "mbowdidge6",
    "createAt": "7/25/2022",
    "slug": "bifurcated",
    "averageRating": 3.82
  },
  {
    "id": "162f3ccb-a119-4c7f-a1b2-ad9687c65c32",
    "category": "Plumbing & Medical Gas",
    "colors": "Aquamarine",
    "photo": "http://dummyimage.com/201x100.png/dddddd/000000",
    "name": "Mushroom - Shitake, Fresh",
    "price": 64,
    "description": "sapien varius ut blandit non interdum",
    "weight": 33.05,
    "specs": "tristique fusce congue diam id ornare imperdiet",
    "branch": "Zoomcast",
    "origin": "platea dictumst etiam faucibus cursus",
    "discount": 9.3,
    "shop": "Skipfire",
    "user": "sbruggeman7",
    "createAt": "3/3/2022",
    "slug": "help-desk",
    "averageRating": 1.7
  },
  {
    "id": "7a271835-dcc8-4615-8c8e-dd9158280c21",
    "category": "Landscaping & Irrigation",
    "colors": "Mauv",
    "photo": "http://dummyimage.com/150x100.png/ff4444/ffffff",
    "name": "Pork - Belly Fresh",
    "price": 3,
    "description": "donec dapibus duis at velit",
    "weight": 31.47,
    "specs": "id pretium iaculis diam erat fermentum justo nec",
    "branch": "Twitterworks",
    "origin": "hac habitasse platea dictumst morbi vestibulum velit id",
    "discount": 6.01,
    "shop": "Gigazoom",
    "user": "mkynd8",
    "createAt": "1/14/2022",
    "slug": "composite",
    "averageRating": 1.03
  },
  {
    "id": "c38784a6-ef75-4ffe-bcb7-fff3bf5cb98f",
    "category": "EIFS",
    "colors": "Orange",
    "photo": "http://dummyimage.com/191x100.png/cc0000/ffffff",
    "name": "Flour - Masa De Harina Mexican",
    "price": 7,
    "description": "amet erat nulla tempus vivamus in felis eu",
    "weight": 88.99,
    "specs": "ut rhoncus aliquet pulvinar sed nisl nunc",
    "branch": "Pixoboo",
    "origin": "magna ac consequat metus sapien ut nunc vestibulum",
    "discount": 2.48,
    "shop": "Oyonder",
    "user": "blammas9",
    "createAt": "6/11/2022",
    "slug": "secondary",
    "averageRating": 2.73
  },
  {
    "id": "54170a13-8c2b-4bd3-8e41-51119aa490f0",
    "category": "Plumbing & Medical Gas",
    "colors": "Puce",
    "photo": "http://dummyimage.com/105x100.png/cc0000/ffffff",
    "name": "Everfresh Products",
    "price": 86,
    "description": "duis bibendum felis sed interdum venenatis turpis enim",
    "weight": 69.14,
    "specs": "ac nulla sed vel enim sit amet nunc viverra",
    "branch": "Oodoo",
    "origin": "mattis pulvinar nulla pede ullamcorper augue a suscipit",
    "discount": 9.03,
    "shop": "Gabspot",
    "user": "vweisera",
    "createAt": "8/13/2021",
    "slug": "Grass-roots",
    "averageRating": 3.07
  },
  {
    "id": "23f9e9cf-f891-4546-a60d-baaebb9e048d",
    "category": "Termite Control",
    "colors": "Khaki",
    "photo": "http://dummyimage.com/187x100.png/dddddd/000000",
    "name": "Apple - Fuji",
    "price": 95,
    "description": "odio in hac habitasse platea dictumst maecenas ut",
    "weight": 54.44,
    "specs": "nulla suscipit ligula in lacus curabitur at ipsum ac",
    "branch": "Wikibox",
    "origin": "amet cursus id turpis integer aliquet massa",
    "discount": 1.33,
    "shop": "Babbleopia",
    "user": "bolivellib",
    "createAt": "7/19/2022",
    "slug": "functionalities",
    "averageRating": 3.87
  },
  {
    "id": "16dbb113-a4e7-4ff2-ac22-857d0ef39ac9",
    "category": "Framing (Steel)",
    "colors": "Goldenrod",
    "photo": "http://dummyimage.com/132x100.png/ff4444/ffffff",
    "name": "Wine - Rosso Toscano Igt",
    "price": 97,
    "description": "ut tellus nulla ut erat id",
    "weight": 61.71,
    "specs": "congue vivamus metus arcu adipiscing",
    "branch": "Centizu",
    "origin": "sem duis aliquam convallis nunc proin at turpis a",
    "discount": 9.02,
    "shop": "Eamia",
    "user": "cjakubovskic",
    "createAt": "11/7/2021",
    "slug": "hybrid",
    "averageRating": 4.48
  },
  {
    "id": "a882ecdf-f59a-4dc3-8bf7-3b2d6c941f49",
    "category": "Structural & Misc Steel Erection",
    "colors": "Turquoise",
    "photo": "http://dummyimage.com/243x100.png/dddddd/000000",
    "name": "Coffee - 10oz Cup 92961",
    "price": 64,
    "description": "erat fermentum justo nec condimentum",
    "weight": 8.02,
    "specs": "nunc vestibulum ante ipsum primis in faucibus orci",
    "branch": "JumpXS",
    "origin": "vestibulum sit amet cursus id turpis",
    "discount": 1.28,
    "shop": "Oyoloo",
    "user": "lmorcombed",
    "createAt": "3/1/2022",
    "slug": "Triple-buffered",
    "averageRating": 1.63
  },
  {
    "id": "568ab15b-eab9-4634-b5a1-9960800a5251",
    "category": "Wall Protection",
    "colors": "Purple",
    "photo": "http://dummyimage.com/132x100.png/cc0000/ffffff",
    "name": "Apricots - Halves",
    "price": 2,
    "description": "libero convallis eget eleifend luctus ultricies",
    "weight": 24.65,
    "specs": "lectus pellentesque eget nunc donec quis",
    "branch": "Skaboo",
    "origin": "diam vitae quam suspendisse potenti nullam porttitor",
    "discount": 7.58,
    "shop": "Kimia",
    "user": "jopdenorthe",
    "createAt": "5/20/2022",
    "slug": "analyzer",
    "averageRating": 4.23
  },
  {
    "id": "91741c9f-ae66-4c33-b3c4-be62c3df1ca0",
    "category": "Ornamental Railings",
    "colors": "Yellow",
    "photo": "http://dummyimage.com/111x100.png/dddddd/000000",
    "name": "V8 - Tropical Blend",
    "price": 70,
    "description": "in hac habitasse platea dictumst aliquam augue",
    "weight": 47.26,
    "specs": "sollicitudin vitae consectetuer eget rutrum at lorem integer",
    "branch": "Tazzy",
    "origin": "proin risus praesent lectus vestibulum quam sapien varius ut",
    "discount": 4.32,
    "shop": "Rhyloo",
    "user": "kbroadyf",
    "createAt": "5/28/2022",
    "slug": "next generation",
    "averageRating": 4.05
  },
  {
    "id": "006aa637-7fe7-4e63-8027-e226b50d3e46",
    "category": "Drywall & Acoustical (MOB)",
    "colors": "Pink",
    "photo": "http://dummyimage.com/206x100.png/dddddd/000000",
    "name": "Bread - Calabrese Baguette",
    "price": 66,
    "description": "integer pede justo lacinia eget tincidunt eget",
    "weight": 13.58,
    "specs": "vel ipsum praesent blandit lacinia erat vestibulum sed magna",
    "branch": "Yambee",
    "origin": "massa volutpat convallis morbi odio odio elementum eu interdum",
    "discount": 3.68,
    "shop": "Topicblab",
    "user": "mkierang",
    "createAt": "5/26/2022",
    "slug": "Multi-layered",
    "averageRating": 2.81
  },
  {
    "id": "7fe63150-1128-4aaa-bb46-eda87ca5dd08",
    "category": "Wall Protection",
    "colors": "Turquoise",
    "photo": "http://dummyimage.com/239x100.png/ff4444/ffffff",
    "name": "Wine - Tio Pepe Sherry Fino",
    "price": 14,
    "description": "ut rhoncus aliquet pulvinar sed nisl nunc",
    "weight": 61.63,
    "specs": "in est risus auctor sed tristique in",
    "branch": "Thoughtblab",
    "origin": "faucibus orci luctus et ultrices posuere cubilia curae mauris viverra",
    "discount": 9.01,
    "shop": "Youfeed",
    "user": "kbennetonh",
    "createAt": "10/25/2021",
    "slug": "multimedia",
    "averageRating": 2.81
  },
  {
    "id": "3bc879d5-bd95-40ba-b56f-4fe6983f7245",
    "category": "Retaining Wall and Brick Pavers",
    "colors": "Purple",
    "photo": "http://dummyimage.com/204x100.png/cc0000/ffffff",
    "name": "Island Oasis - Magarita Mix",
    "price": 26,
    "description": "quis orci nullam molestie nibh in lectus pellentesque at",
    "weight": 49.77,
    "specs": "sapien arcu sed augue aliquam erat volutpat in congue",
    "branch": "Quire",
    "origin": "ut tellus nulla ut erat id mauris vulputate elementum",
    "discount": 1.1,
    "shop": "Rooxo",
    "user": "dlindneri",
    "createAt": "5/9/2022",
    "slug": "secured line",
    "averageRating": 2.11
  },
  {
    "id": "fc51a675-8922-4c54-890b-1e63456d261f",
    "category": "Hard Tile & Stone",
    "colors": "Pink",
    "photo": "http://dummyimage.com/102x100.png/cc0000/ffffff",
    "name": "Scallops - 20/30",
    "price": 67,
    "description": "ut blandit non interdum in ante vestibulum ante ipsum primis",
    "weight": 57.29,
    "specs": "pede ac diam cras pellentesque",
    "branch": "Pixonyx",
    "origin": "mi integer ac neque duis bibendum morbi",
    "discount": 6.96,
    "shop": "Kazu",
    "user": "bbonfieldj",
    "createAt": "1/6/2022",
    "slug": "zero administration",
    "averageRating": 1.8
  },
  {
    "id": "f404e5d8-16eb-4b3e-a488-d8f57dc1ac2f",
    "category": "Masonry & Precast",
    "colors": "Red",
    "photo": "http://dummyimage.com/192x100.png/5fa2dd/ffffff",
    "name": "Mcguinness - Blue Curacao",
    "price": 43,
    "description": "lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi",
    "weight": 45.63,
    "specs": "et ultrices posuere cubilia curae",
    "branch": "Omba",
    "origin": "penatibus et magnis dis parturient montes nascetur",
    "discount": 9.71,
    "shop": "Wordtune",
    "user": "treedek",
    "createAt": "9/14/2021",
    "slug": "web-enabled",
    "averageRating": 1.7
  },
  {
    "id": "8c280593-cee8-411e-bc80-2290a9b98d7e",
    "category": "Roofing (Metal)",
    "colors": "Purple",
    "photo": "http://dummyimage.com/211x100.png/5fa2dd/ffffff",
    "name": "Ocean Spray - Ruby Red",
    "price": 15,
    "description": "lectus vestibulum quam sapien varius ut blandit non interdum",
    "weight": 76.54,
    "specs": "mauris vulputate elementum nullam varius nulla facilisi",
    "branch": "Skyba",
    "origin": "in leo maecenas pulvinar lobortis",
    "discount": 9.13,
    "shop": "Tekfly",
    "user": "agotcherl",
    "createAt": "1/10/2022",
    "slug": "contingency",
    "averageRating": 3.43
  },
  {
    "id": "bff14e4d-ad55-49ef-8f6c-31e742c697b5",
    "category": "Fire Sprinkler System",
    "colors": "Khaki",
    "photo": "http://dummyimage.com/182x100.png/ff4444/ffffff",
    "name": "Jam - Strawberry, 20 Ml Jar",
    "price": 47,
    "description": "condimentum id luctus nec molestie sed",
    "weight": 27.26,
    "specs": "in libero ut massa volutpat convallis morbi odio",
    "branch": "Skinte",
    "origin": "tortor sollicitudin mi sit amet",
    "discount": 3.2,
    "shop": "Skalith",
    "user": "wbenardeaum",
    "createAt": "12/13/2021",
    "slug": "Digitized",
    "averageRating": 4.79
  },
  {
    "id": "95d89a24-cc97-42dc-b309-2556a753994c",
    "category": "Temp Fencing, Decorative Fencing and Gates",
    "colors": "Purple",
    "photo": "http://dummyimage.com/237x100.png/dddddd/000000",
    "name": "Mackerel Whole Fresh",
    "price": 17,
    "description": "nibh in quis justo maecenas rhoncus aliquam",
    "weight": 16.95,
    "specs": "eleifend luctus ultricies eu nibh quisque",
    "branch": "Mynte",
    "origin": "faucibus orci luctus et ultrices posuere cubilia curae duis faucibus",
    "discount": 1.37,
    "shop": "Dynabox",
    "user": "cbramern",
    "createAt": "3/13/2022",
    "slug": "Ameliorated",
    "averageRating": 3.89
  },
  {
    "id": "b8cfdbcd-58a3-4f53-bda8-ce405bc22176",
    "category": "Doors, Frames & Hardware",
    "colors": "Turquoise",
    "photo": "http://dummyimage.com/162x100.png/ff4444/ffffff",
    "name": "Wine - Niagara Peninsula Vqa",
    "price": 76,
    "description": "orci pede venenatis non sodales sed",
    "weight": 37.22,
    "specs": "etiam justo etiam pretium iaculis justo in",
    "branch": "Dynava",
    "origin": "vulputate elementum nullam varius nulla facilisi cras non velit nec",
    "discount": 8.36,
    "shop": "Zoozzy",
    "user": "ejuorioo",
    "createAt": "3/30/2022",
    "slug": "Graphic Interface",
    "averageRating": 3.96
  },
  {
    "id": "deba30a3-df66-420c-93fc-1067e969d95b",
    "category": "Electrical and Fire Alarm",
    "colors": "Green",
    "photo": "http://dummyimage.com/154x100.png/cc0000/ffffff",
    "name": "Crush - Orange, 355ml",
    "price": 37,
    "description": "quisque porta volutpat erat quisque erat eros viverra eget",
    "weight": 45.52,
    "specs": "ante ipsum primis in faucibus orci luctus et ultrices",
    "branch": "Tazz",
    "origin": "nam ultrices libero non mattis pulvinar nulla pede ullamcorper",
    "discount": 4.44,
    "shop": "Quatz",
    "user": "pdruganp",
    "createAt": "5/3/2022",
    "slug": "encryption",
    "averageRating": 3.9
  },
  {
    "id": "5df77098-3ed7-418e-9212-9f26afdb3bd0",
    "category": "Retaining Wall and Brick Pavers",
    "colors": "Crimson",
    "photo": "http://dummyimage.com/126x100.png/ff4444/ffffff",
    "name": "Stock - Veal, White",
    "price": 84,
    "description": "rhoncus dui vel sem sed sagittis nam congue risus",
    "weight": 46.04,
    "specs": "ultrices vel augue vestibulum ante ipsum primis in faucibus",
    "branch": "Browsecat",
    "origin": "eu mi nulla ac enim in",
    "discount": 7.37,
    "shop": "Jatri",
    "user": "klathwellq",
    "createAt": "7/19/2022",
    "slug": "Future-proofed",
    "averageRating": 2.19
  },
  {
    "id": "237cf010-4052-419c-9f90-0c213ba33b52",
    "category": "Fire Protection",
    "colors": "Violet",
    "photo": "http://dummyimage.com/107x100.png/dddddd/000000",
    "name": "Longos - Chicken Curried",
    "price": 8,
    "description": "non interdum in ante vestibulum ante",
    "weight": 4.3,
    "specs": "semper sapien a libero nam dui proin",
    "branch": "Meevee",
    "origin": "fringilla rhoncus mauris enim leo rhoncus sed vestibulum",
    "discount": 5.23,
    "shop": "Feednation",
    "user": "idagworthyr",
    "createAt": "12/31/2021",
    "slug": "benchmark",
    "averageRating": 1.54
  },
  {
    "id": "85614bfe-97be-40f3-b9e4-5662a4d3a2ce",
    "category": "Plumbing & Medical Gas",
    "colors": "Teal",
    "photo": "http://dummyimage.com/234x100.png/cc0000/ffffff",
    "name": "Pasta - Ravioli",
    "price": 42,
    "description": "amet diam in magna bibendum imperdiet",
    "weight": 79.3,
    "specs": "sem mauris laoreet ut rhoncus aliquet pulvinar sed",
    "branch": "Livetube",
    "origin": "ultrices posuere cubilia curae nulla dapibus dolor",
    "discount": 1.29,
    "shop": "Wordware",
    "user": "efulops",
    "createAt": "12/16/2021",
    "slug": "Secured",
    "averageRating": 2.39
  },
  {
    "id": "0cc28173-c75a-4943-84f5-1bf9deb0a65c",
    "category": "Hard Tile & Stone",
    "colors": "Pink",
    "photo": "http://dummyimage.com/151x100.png/ff4444/ffffff",
    "name": "Jolt Cola",
    "price": 66,
    "description": "ut tellus nulla ut erat id mauris",
    "weight": 64.24,
    "specs": "quis turpis eget elit sodales scelerisque mauris sit",
    "branch": "Eire",
    "origin": "nam nulla integer pede justo lacinia eget",
    "discount": 8.38,
    "shop": "Livepath",
    "user": "bsimpkisst",
    "createAt": "3/11/2022",
    "slug": "knowledge user",
    "averageRating": 3.36
  }
]
